name: Create Tag on Merge to master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Create tag
        uses: Srikanthjh/jenkinsgit@2.0.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
